# version: '3'

services:
  db:
    build: ./requirments/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inceptionnet

  wordpress:
    depends_on:
      - db
    build: ./requirments/wordpress
    image: wordpress
    env_file:
      - .env
    container_name: wordpress
    restart: always
    volumes:
      - ./requirments/wordpress/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - wordpress:/var/www/html
    networks:
      - inceptionnet

  nginx:
    depends_on:
      - wordpress
    build: ./requirments/nginx
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./requirments/nginx/default:/etc/nginx/sites-available/default
      - wordpress:/var/www/html
    networks:
      - inceptionnet

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/smaei/42/volumes/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/smaei/42/volumes/mariadb
networks:
  inceptionnet:
