# version: '3'

services:
  db:
  #   image: mysql:5.7 # mysqlのバージョンは適宜変えてください
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: examplepassword
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_USER: wordpress
  #     MYSQL_PASSWORD: examplepassword
    build: ./requirments/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    networks:
      - inceptionnet

  wordpress:
    depends_on:
      - db
  #   image: wordpress:latest
  #   volumes:
  #     - ./wordpress:/var/www/html
  #   restart: always
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: examplepassword
  #     WORDPRESS_DB_NAME: wordpress
  #   ports:
  #     - "8000:80"
    build: ./requirments/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    volumes:
      - ./requirments/wordpress/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - wordpress:/var/www/html
    networks:
      - inceptionnet

  nginx:
    # image: nginx:latest
    # ports:
    #   - "80:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
    build: ./requirments/nginx
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./requirments/nginx/default:/etc/nginx/sites-available/default
      - wordpress:/var/www/html
    networks:
      - inceptionnet


volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/smaei/42/inception/volume
networks:
  inceptionnet:
